version: '3.9'

services:
    casheer:
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: casheer-e2e
        command: --server-address 0.0.0.0 --server-port 8033
        ports:
            - 8033:8033
