version: '3.9'

services:
    casheer:
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: casheer-e2e
        # Make sure ports from command and ports match.
        env_file:
            - ./configs/e2e.env
        ports:
            - 6597:6597
        volumes:
            - ./${DBNAME:-casheer.e2e.db}:/externaldeps/casheer.db
