version: '3.9'

services:
    casheer:
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: casheer-e2e

        # Make sure ports from command and ports match. If desired, create a .env
        # file for docker compose to not have to manage it manually.
        command: --server-address 0.0.0.0 --server-port 6597 --sqlite-db /externaldeps/casheer.db
        ports:
            - 6597:6597
