version: '3.9'

services:
    casheer:
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: casheer-dev
        command: --server-address 0.0.0.0 --server-port 8033 --sqlite-db /externaldeps/casheer.db
        ports:
            - 8033:8033
