version: '3.9'

services:
    casheer:
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: casheer-dev
        environment:
            - CASHEER_SERVER_SCHEME=http
            - CASHEER_SERVER_ADDRESS=0.0.0.0
            - CASHEER_SERVER_PORT=8033
            - CASHEER_SQLITEDATABASE_FILE=/home/nonroot/casheer.db
            - CASHEER_SQLITEDATABASE_MIGRATION=/home/nonroot/scripts/sqlite/
            - CASHEER_SQLITEDATABASE_CREATEIFEMPTY=true
            - CASHEER_APIPATHS_ENTRIES=entries/
            - CASHEER_APIPATHS_EXPENSES=expenses/
            - CASHEER_APIPATHS_DEBTS=debts/
            - CASHEER_APIPATHS_TOTALS=totals/
        ports:
            - 8033:8033
        volumes:
            - ./scripts/sqlite/:/home/nonroot/scripts/sqlite/
