version: '3.9'

services:
    casheer:
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: casheer-dev
        env_file:
            - ./configs/dev.env
        ports:
            - 8033:8033
