version: '3.9'

services:
    casheer:
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: casheer-e2e
        # Make sure ports from command and ports match.
        environment:
            - CASHEER_SERVER_SCHEME=http
            - CASHEER_SERVER_ADDRESS=0.0.0.0
            - CASHEER_SERVER_PORT=6597
            - CASHEER_SQLITE_FILE=/externaldeps/casheer.db
        ports:
            - 6597:6597
        volumes:
            - ./${DBNAME:-casheer.e2e.db}:/externaldeps/casheer.db
