openapi: 3.0.3
info:
  title: Casheer
  description: |-
    This is a money transactions manager.
  termsOfService: http://swagger.io/terms/
  contact:
    email: qscxzsewqazxcde@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
paths:
  /debts/:
    get:
      summary: List all existing debts
      description: This operation will list all existing debts.
      operationId: listDebts
      parameters:
        - in: query
          name: person
          description: The person in the returned debts must match the parameter.
          required: false
          schema:
            type: string
            example: John Cena
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "./components/schemas/debts.yaml#/Debt"
                  links:
                    type: object
                    properties:
                      self:
                        type: string
                        example: "http://dumblinks.com/debts/"
                      home:
                        type: object
                        properties:
                          href:
                            type: string
                            example: "http://dumblinks.com/home"
                          title:
                            type: string
                            example: Home page of casheer API.

        "400":
          description: Invalid debt request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    oneOf:
                      - $ref: "./components/schemas/errors.yaml#/invalidQueryParamsError"
                      - $ref: "./components/schemas/errors.yaml#/invalidURLError"
        "500":
          $ref: "./responses/errors.yaml#/unexpectedError"
    post:
      summary: Create a new debt
      description: This operation will create a new debt, given the provided debt information is valid.
      operationId: createDebts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  $ref: "./components/schemas/debts.yaml#/CreateDebt"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "./components/schemas/debts.yaml#/DebtWithLink"
        "400":
          description: Invalid debt request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    oneOf:
                      - $ref: "./components/schemas/errors.yaml#/invalidRequestBodyError"
        "422":
          description: Invalid debt sent in request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: "./components/schemas/errors.yaml#/invalidResourceError"
        "500":
          $ref: "./responses/errors.yaml#/unexpectedError"
  /debts/{dbtid}:
    get:
      summary: Retrieve the data of an existing debt.
      description: This operation will return the data of an existing debt, given the provided debt id exists.
      operationId: getDebt
      parameters:
        - in: path
          name: dbtid
          description: The ID of the debt to be retrieved.
          required: true
          schema:
            type: number
            example: 500
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "./components/schemas/debts.yaml#/DebtWithLink"
        "404":
          description: Debt was not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    oneOf:
                      - $ref: "./components/schemas/errors.yaml#/resourceNotFoundError"
        "500":
          $ref: "./responses/errors.yaml#/unexpectedError"
    patch:
      summary: Update the data of an existing debt.
      description: This operation will update the data of an existing debt, given the provided debt exists.
      operationId: updateDebt
      parameters:
        - in: path
          name: dbtid
          description: The ID of the debt to be retrieved.
          required: true
          schema:
            type: number
            example: 500
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  $ref: "./components/schemas/debts.yaml#/CreateDebt"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "./components/schemas/debts.yaml#/DebtWithLink"
        "404":
          description: Debt was not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    oneOf:
                      - $ref: "./components/schemas/errors.yaml#/resourceNotFoundError"
        "422":
          description: Invalid debt sent in request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: "./components/schemas/errors.yaml#/invalidResourceError"
        "500":
          $ref: "./responses/errors.yaml#/unexpectedError"
    delete:
      summary: Delete an existing debt.
      description: This operation will remove an existing debt, given the provided debt exists.
      operationId: updateDebt
      parameters:
        - in: path
          name: dbtid
          description: The ID of the debt to be retrieved.
          required: true
          schema:
            type: number
            example: 500
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "./components/schemas/debts.yaml#/Debt"
        "404":
          description: Debt was not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    oneOf:
                      - $ref: "./components/schemas/errors.yaml#/resourceNotFoundError"
        "500":
          $ref: "./responses/errors.yaml#/unexpectedError"
