apipaths:
    debts: debts/
    entries: entries/
    expenses: expenses/
    totals: totals/
server:
    address: 127.0.0.1
    port: 6597
    scheme: http
sqlite_database:
    file: casheer.e2e.db
    migration: ./scripts/sqlite/001_tables.up.sql
