name: Go package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build
        run: go build -o casheer ./cmd/

      - name: Test
        run: go test -v ./internal/...

  run-end-to-end-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Docker Compose Build
        run: docker compose build

      - name: Docker Compose Up
        run: docker compose up

      - name: Run e2e tests
        run: go test -v ./e2e/...
