name: Go package

on:
  push:
    branches:
      - main
      - refactor
  pull_request:
    branches:
      - main
      - refactor

jobs:
  build-and-run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build
        run: go build -o casheer ./cmd/

      - name: Test
        run: go test -v ./internal/...

  run-end-to-end-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run end to end tests
        working-directory: .
        run: bash test_e2e.sh
